# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Marlon M/Documents/UnB/5semestre/SD1/VHDL/my_projects/and_4/and_4.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Marlon M/Documents/UnB/5semestre/SD1/VHDL/my_projects/and_4/and_4.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  {C:/Users/Marlon M/Documents/UnB/5semestre/SD1/VHDL/my_projects/and_4/and_4.srcs/sources_1/new/and_4_entity.vhd}
  {C:/Users/Marlon M/Documents/UnB/5semestre/SD1/VHDL/my_projects/and_4/and_4.srcs/sources_1/new/test_and_4.vhd}
}
synth_design -top test_and_4 -part xc7a35tcpg236-1
write_checkpoint -noxdef test_and_4.dcp
catch { report_utilization -file test_and_4_utilization_synth.rpt -pb test_and_4_utilization_synth.pb }
